version: '3' # 指定docker-compose版本

services:
  nginx:    # 服务名称  用户自定义
    image: nginx:latest   # 镜像版本
    ports:
      - 80:80     # 暴露端口（宿主:容器）
    volumes:      # 挂载
      - /root/nginx/html:/usr/share/nginx/html
      - /root/nginx/nginx.conf:/etc/nginx/nginx.conf
    privileged: true  # 这个必须要，解决nginx的文件调用的权限问题
  mysql:
    image: mysql:5.7.19
    ports:
      - 3306:3306
    environment:    # 指定 root 用户的密码
      - MYSQL_ROOT_PASSWORD=123456
#  redis:
#    image: redis:latest
  websocket:
    image: websocket:latest
    build: .    # 表示以当前目录下的Dockerfile开始构建镜像
    ports:
      - 8080:8080
    depends_on:   # 依赖于mysql、redis，其实可以不填，默认已经表示可以
      - mysql
#      - redis
